1. Simple Structure

In [9]:
# HINTS
# 1. Use pandas.read_json()
# 2. Export to CSV as path: 'destination/json'
simple_json_file_path = "simple_structure.json"
import pandas as pd
import json
df_simple = pd.read_json(simple_json_file_path)
print(df_simple)

   id    name  math  physics  chemistry
0  A1     Jim    60       66         61
1  A2  Dwight    89       76         51
2  A3   Kevin    79       90         78

2. Multiple Level

In [2]:
# HINTS
# 1. Use pandas json_normalize to read data from record_path
# 2. Export to CSV as path: 'destination/json'
import pandas as pd
import json
multiple_level_json_file_path = "multiple_level.json"
with open (file=multiple_level_json_file_path, mode="r") as f:
    data = json.load(f)
print(data)

{'school_name': 'Dunder Miflin', 'class': 'Year 1', 'students': [{'id': 'A1', 'name': 'Jim', 'math': 60, 'physics': 66, 'chemistry': 61}, {'id': 'A2', 'name': 'Dwight', 'math': 89, 'physics': 76, 'chemistry': 51}, {'id': 'A3', 'name': 'Kevin', 'math': 79, 'physics': 90, 'chemistry': 78}]}

In [3]:
type(data)

dict

In [ ]:
#Hardcode
df = pd.json_normalize(data=data['students'])
df['class'] = data['class']
df['school_name'] = data['school_name']
df

   id    name  math  physics  chemistry   class    school_name
0  A1     Jim    60       66         61  Year 1  Dunder Miflin
1  A2  Dwight    89       76         51  Year 1  Dunder Miflin
2  A3   Kevin    79       90         78  Year 1  Dunder Miflin

In [5]:
data['students']

[{'id': 'A1', 'name': 'Jim', 'math': 60, 'physics': 66, 'chemistry': 61},
 {'id': 'A2', 'name': 'Dwight', 'math': 89, 'physics': 76, 'chemistry': 51},
 {'id': 'A3', 'name': 'Kevin', 'math': 79, 'physics': 90, 'chemistry': 78}]

In [11]:
#option 2
record_path='students'
meta=['school_name', 'class']
df = pd.json_normalize(data=data, record_path=record_path, meta=meta, record_prefix='students_')
df

,students_id,students_name,students_math,students_physics,students_chemistry,school_name,class
0,A1,Jim,60,66,61,Dunder Miflin,Year 1
1,A2,Dwight,89,76,51,Dunder Miflin,Year 1
2,A3,Kevin,79,90,78,Dunder Miflin,Year 1

3. Nested Levels

In [3]:
# HINTS
# Approach 1: use record_path + meta
# 1. Open the load JSON into dictionary 
# 2. Use pandas json_normalize to read data from record_path
# 3. Export to CSV as path: 'destination/json'
nested_level_json_file_path = "nested_level.json"

with open(file=nested_level_json_file_path, mode='r') as f:
    data= json.load(f)
data

{'school_name': 'Dunder Miflin',
 'class': {'level': 12, 'room': 'K1.01', 'teacher': 'John'},
 'students': [{'id': 'A1',
   'name': 'Jim',
   'grade': {'math': 60, 'physics': 66, 'chemistry': 61}},
  {'id': 'A2',
   'name': 'Dwight',
   'grade': {'math': 89, 'physics': 76, 'chemistry': 51}},
  {'id': 'A3',
   'name': 'Kevin',
   'grade': {'math': 79, 'physics': 90, 'chemistry': 78}}]}

In [4]:
record_path='students'
meta=['school_name', ['class', 'level'], ['class','room'], ['class', 'teacher']]
df = pd.json_normalize(data=data, record_path=record_path, meta=meta)
df

,id,name,grade.math,grade.physics,grade.chemistry,school_name,class.level,class.room,class.teacher
0,A1,Jim,60,66,61,Dunder Miflin,12,K1.01,John
1,A2,Dwight,89,76,51,Dunder Miflin,12,K1.01,John
2,A3,Kevin,79,90,78,Dunder Miflin,12,K1.01,John

In [ ]:
# HINTS
# Approach 2: Read seperately and cross join
# 1. Open the load JSON into dictionary 
# 2. Use pandas json_normalize to read data from record_path
# 3. Export to CSV as path: 'destination/json'

In [5]:
df1 = pd.json_normalize(data=data)
df1

,school_name,students,class.level,class.room,class.teacher
0,Dunder Miflin,"[{'id': 'A1', 'name': 'Jim', 'grade': {'math':...",12,K1.01,John

In [6]:
df2 = pd.json_normalize(data=data['students'])
df2

   id    name  grade.math  grade.physics  grade.chemistry
0  A1     Jim          60             66               61
1  A2  Dwight          89             76               51
2  A3   Kevin          79             90               78

In [7]:
df = pd.merge(left=df1, right=df2, how='cross')
df = df.drop(columns='students')
df

,school_name,class.level,class.room,class.teacher,id,name,grade.math,grade.physics,grade.chemistry
0,Dunder Miflin,12,K1.01,John,A1,Jim,60,66,61
1,Dunder Miflin,12,K1.01,John,A2,Dwight,89,76,51
2,Dunder Miflin,12,K1.01,John,A3,Kevin,79,90,78